import { Montserrat } from 'next/font/google';
import { notFound } from 'next/navigation';

import { Footer, Header } from '@/components';

import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Montserrat({
  subsets: ['latin'],
  display: 'swap',
});
export default function RootLayout({ children, params }: { children: React.ReactNode; params: any }) {

  return (
    <html className={inter.className}>
      <body className={' container m-auto'}>
        <Header />
        <div className="mt-24">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
