import { useLocale } from 'next-intl';
import { Inter } from 'next/font/google';
import { notFound } from 'next/navigation';

import { Header } from '@/components';

import "./../globals.css";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, params }: { children: React.ReactNode; params: any }) {
  const locale = useLocale();
  if (params.locale !== locale) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body className={' m-auto container'}>
        {/* <Header /> */}
        {children}
      </body>
    </html>
  );
}
